apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: www
  name: www
spec:
  containers:
  - image: http
    name: www
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
